//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionQR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clientes()
        {
            this.Usuarios_quejas = new HashSet<Usuarios_quejas>();
            this.Usuarios_reclamaciones = new HashSet<Usuarios_reclamaciones>();
        }
    
        public int Id { get; set; }
        public string Nombres_Cliente { get; set; }
        public string Apellidos_Cliente { get; set; }
        public string Teléfono { get; set; }
        public string Direccion { get; set; }
        public string Provincia { get; set; }
        public string Sector { get; set; }
        public string Email { get; set; }
        public int Estado { get; set; }
    
        public virtual Estado Estado1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuarios_quejas> Usuarios_quejas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuarios_reclamaciones> Usuarios_reclamaciones { get; set; }
    }
}
