//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionQR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quejas
    {
        public int Id { get; set; }
        public int Id_Cliente { get; set; }
        public string Usuario_Quejas { get; set; }
        public string Tipo_Quejas { get; set; }
        public string Departamento_Queja { get; set; }
        public string Encargado_Queja { get; set; }
        public System.DateTime Fecha_Queja { get; set; }
        public System.DateTime Hora_Queja { get; set; }
        public string Departamento_Respuesta { get; set; }
        public System.DateTime Fecha_Respuesta { get; set; }
        public string Estatus_Quejas { get; set; }
        public string Comentarios_Queja { get; set; }
    }
}
