//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionQR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios_reclamaciones
    {
        public int Id { get; set; }
        public long Usuario_reclamo { get; set; }
        public int Clave { get; set; }
        public int Departamento_Reclamacion { get; set; }
        public System.DateTime Fecha_Reclamacion { get; set; }
        public System.DateTime Hora_Reclamacion { get; set; }
        public int Rol { get; set; }
        public int Puesto { get; set; }
        public int Cliente { get; set; }
        public int Producto { get; set; }
        public int Estado { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Departamentos Departamentos { get; set; }
        public virtual Estado Estado1 { get; set; }
        public virtual Producto Producto1 { get; set; }
        public virtual Puesto Puesto1 { get; set; }
        public virtual Rol Rol1 { get; set; }
    }
}
